import prettier from "prettier"

async function fetchAndConcatenate(outputFile: string, urls: string[]) {
  const contents: string[] = []

  for (const url of urls) {
    try {
      console.log(`Fetching: ${url}`)
      const response = await fetch(url)

      if (!response.ok) {
        console.error(`Failed to fetch ${url}: ${response.statusText}`)
        continue
      }

      let text = await response.text()

      text = text
        .replace(/<br \/>/g, "\n") // Remove <br /> tags
        .replace(/<br\/>/g, "\n") // Remove <br/> tags
        .replace(/<br>/g, "\n") // Remove <br> tags
        .replace(/<hr \/>/g, "\n") // Remove <hr /> tags
        .replace(/<hr\/>/g, "\n") // Remove <hr/> tags
        .replace(/<hr>/g, "\n") // Remove <hr> tags
        .replace(/\n{3,}/g, "\n\n") // Remove multiple newlines
        .replace(/```typescript\s+copy/g, "```ts") // Remove copy from typescript code blocks
        .replace(/^---\s*title:\s*(.+?)\s*---/m, (_, title) => `# ${title.trim()}`) // Replace --- title: Title --- with # Title
        .replace(/^import\s+[\w{}\s,*]+\s+from\s+['"][^'"]*(astro|mdx)[^'"]*['"];?$/gm, "") // Remove import statements from Astro and MDX files

      // Format with Prettier
      text = await prettier.format(text, { parser: "mdx" })

      contents.push(text)
    } catch (error) {
      console.error(`Error fetching ${url}:`, error)
    }
  }

  try {
    await Bun.write(outputFile, contents.join("\n\n---\n\n"))
    console.log(`Successfully fetched and wrote to ${outputFile}`)
  } catch (error) {
    console.error(`Error writing to ${outputFile}:`, error)
  }
}

// Drizzle
fetchAndConcatenate("drizzle-doc.md", [
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/overview.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/sql-schema-declaration.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/connect-overview.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/data-querying.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/migrations.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/get-started-postgresql.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/column-types/pg.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/indexes-constraints.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/sequences.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/views.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/schemas.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/rls.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/extensions/pg.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/relations.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/kit-overview.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/drizzle-kit-generate.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/drizzle-kit-migrate.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/drizzle-kit-push.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/drizzle-kit-pull.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/drizzle-kit-check.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/drizzle-kit-up.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/drizzle-kit-studio.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/kit-custom-migrations.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/drizzle-config-file.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/rqb.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/select.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/insert.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/update.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/delete.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/operators.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/query-utils.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/joins.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/sql.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/perf-queries.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/perf-serverless.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/set-operations.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/generated-columns.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/transactions.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/batch-api.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/dynamic-query-building.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/read-replicas.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/custom-types.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/goodies.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/eslint-plugin.mdx",
  "https://raw.githubusercontent.com/drizzle-team/drizzle-orm-docs/refs/heads/main/src/content/docs/zod.mdx",
])

// Bun
fetchAndConcatenate("bun-doc.md", [
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/index.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/installation.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/quickstart.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/typescript.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/cli/init.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/cli/bun-create.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/cli/run.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/runtime/loaders.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/runtime/typescript.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/runtime/jsx.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/runtime/env.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/runtime/bun-apis.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/runtime/web-apis.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/runtime/nodejs-apis.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/bundler/executables.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/runtime/plugins.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/runtime/hot.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/runtime/modules.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/runtime/autoimport.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/runtime/bunfig.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/runtime/debugger.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/cli/install.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/cli/add.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/cli/remove.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/cli/update.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/cli/publish.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/cli/outdated.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/cli/link.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/cli/pm.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/install/cache.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/install/workspaces.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/install/lifecycle.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/cli/filter.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/install/lockfile.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/install/registries.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/install/overrides.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/install/patch.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/install/npmrc.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/bundler/index.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/bundler/loaders.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/bundler/plugins.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/bundler/macros.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/bundler/vs-esbuild.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/cli/test.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/test/writing.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/test/hot.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/test/lifecycle.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/test/mocks.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/test/snapshots.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/test/time.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/test/dom.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/test/coverage.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/cli/bunx.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/http.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/fetch.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/websockets.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/workers.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/binary-data.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/streams.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/file-io.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/import-meta.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/sqlite.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/file-system-router.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/tcp.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/udp.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/globals.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/runtime/shell.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/spawn.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/transpiler.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/hashing.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/console.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/ffi.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/cc.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/html-rewriter.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/test.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/utils.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/node-api.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/glob.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/dns.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/semver.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/api/color.md",
  // Guides
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/arraybuffer-to-array.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/arraybuffer-to-blob.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/arraybuffer-to-buffer.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/arraybuffer-to-string.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/arraybuffer-to-typedarray.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/blob-to-arraybuffer.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/blob-to-dataview.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/blob-to-stream.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/blob-to-string.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/blob-to-typedarray.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/buffer-to-arraybuffer.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/buffer-to-blob.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/buffer-to-readablestream.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/buffer-to-string.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/buffer-to-typedarray.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/dataview-to-string.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/typedarray-to-arraybuffer.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/typedarray-to-blob.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/typedarray-to-buffer.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/typedarray-to-dataview.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/typedarray-to-readablestream.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/binary/typedarray-to-string.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/react.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/edgedb.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/prisma.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/discordjs.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/sentry.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/drizzle.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/pm2.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/nuxt.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/qwik.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/astro.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/remix.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/systemd.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/nextjs.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/render.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/sveltekit.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/vite.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/solidstart.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/neon-drizzle.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/hono.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/neon-serverless-postgres.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/elysia.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/docker.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/express.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/ssr-react.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/stric.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/ecosystem/mongoose.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/http/server.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/http/hot.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/http/simple.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/http/cluster.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/http/tls.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/http/fetch.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/http/proxy.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/http/stream-file.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/http/file-uploads.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/http/fetch-unix.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/http/stream-iterator.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/http/stream-node-streams-in-bun.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/add.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/add-git.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/add-peer.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/add-tarball.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/trusted.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/add-optional.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/add-dev.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/jfrog-artifactory.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/yarnlock.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/from-npm-install-to-bun-install.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/workspaces.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/npm-alias.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/git-diff-bun-lockfile.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/cicd.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/custom-registry.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/azure-artifacts.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/install/registry-scope.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/process/stdin.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/process/ctrl-c.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/process/os-signals.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/process/spawn.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/process/argv.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/process/spawn-stderr.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/process/spawn-stdout.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/process/nanoseconds.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/process/ipc.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/read-file/json.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/read-file/exists.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/read-file/buffer.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/read-file/string.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/read-file/mime.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/read-file/uint8array.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/read-file/arraybuffer.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/read-file/watch.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/read-file/stream.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/runtime/import-json.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/runtime/import-toml.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/runtime/shell.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/runtime/tsconfig-paths.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/runtime/timezone.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/runtime/set-env.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/runtime/import-html.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/runtime/read-env.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/runtime/web-debugger.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/runtime/cicd.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/runtime/typescript.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/runtime/vscode-debugger.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/runtime/define-constant.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/streams/to-json.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/streams/node-readable-to-json.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/streams/to-blob.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/streams/node-readable-to-blob.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/streams/to-buffer.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/streams/to-string.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/streams/node-readable-to-string.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/streams/to-typedarray.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/streams/to-arraybuffer.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/streams/node-readable-to-uint8array.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/streams/node-readable-to-arraybuffer.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/streams/to-array.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/mock-functions.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/spy-on.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/testing-library.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/update-snapshots.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/watch-mode.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/snapshot.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/bail.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/skip-tests.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/migrate-from-jest.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/run-tests.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/mock-clock.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/happy-dom.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/timeout.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/todo-tests.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/rerun-each.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/coverage-threshold.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/test/coverage.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/hash-a-password.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/escape-html.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/version.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/base64.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/deep-equals.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/detect-bun.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/import-meta-dir.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/import-meta-file.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/file-url-to-path.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/gzip.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/path-to-file-url.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/which-path-to-executable-bin.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/sleep.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/deflate.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/import-meta-path.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/entrypoint.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/util/main.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/websocket/simple.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/websocket/compression.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/websocket/pubsub.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/websocket/context.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/write-file/unlink.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/write-file/stdout.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/write-file/blob.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/write-file/cat.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/write-file/append.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/write-file/basic.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/write-file/filesink.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/write-file/response.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/write-file/file-cp.md",
  "https://raw.githubusercontent.com/oven-sh/bun/refs/heads/main/docs/guides/write-file/stream.md",
])

// Hono
fetchAndConcatenate("hono-doc.md", [
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/index.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/concepts/routers.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/concepts/web-standard.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/concepts/middleware.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/concepts/stacks.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/getting-started/basic.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/getting-started/cloudflare-workers.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/getting-started/cloudflare-pages.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/getting-started/bun.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/api/hono.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/api/routing.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/api/context.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/api/request.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/api/exception.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/api/presets.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/guides/middleware.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/guides/helpers.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/guides/jsx.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/guides/jsx-dom.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/guides/testing.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/guides/validation.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/guides/rpc.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/guides/best-practices.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/helpers/accepts.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/helpers/adapter.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/helpers/conninfo.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/helpers/cookie.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/helpers/css.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/helpers/dev.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/helpers/factory.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/helpers/html.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/helpers/jwt.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/helpers/ssg.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/helpers/streaming.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/helpers/testing.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/helpers/websocket.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/basic-auth.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/bearer-auth.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/body-limit.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/cache.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/combine.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/compress.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/context-storage.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/cors.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/csrf.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/etag.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/ip-restriction.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/jsx-renderer.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/jwt.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/logger.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/method-override.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/pretty-json.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/request-id.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/secure-headers.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/timeout.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/timing.md",
  "https://raw.githubusercontent.com/honojs/website/refs/heads/main/docs/middleware/builtin/trailing-slash.md",
  "https://raw.githubusercontent.com/honojs/middleware/refs/heads/main/packages/zod-validator/README.md",
  "https://raw.githubusercontent.com/honojs/middleware/refs/heads/main/packages/zod-openapi/README.md",
  "https://raw.githubusercontent.com/honojs/middleware/refs/heads/main/packages/swagger-ui/README.md",
  "https://raw.githubusercontent.com/scalar/scalar/refs/heads/main/packages/hono-api-reference/README.md",
  "https://raw.githubusercontent.com/honojs/middleware/refs/heads/main/packages/trpc-server/README.md",
  "https://raw.githubusercontent.com/ktKongTong/hono-geo-middleware/refs/heads/main/packages/middleware/README.md",
])
